//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaCamp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public Appointment()
        {
            this.AppointmentAcceptions = new HashSet<AppointmentAcception>();
        }
    
        public string Id { get; set; }
        public Nullable<int> PeopleAmount { get; set; }
        public string FoodTypes { get; set; }
        public Nullable<int> PriceRangeStart { get; set; }
        public Nullable<int> PriceRangeEnd { get; set; }
        public bool AllowAnonymous { get; set; }
        public Nullable<System.DateTime> CreatTimeUtc { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Name { get; set; }
        public string CreaterId { get; set; }
        public Nullable<System.DateTime> EatTime { get; set; }
        public bool IsOver { get; set; }
        public bool IsGo { get; set; }
    
        public virtual ICollection<AppointmentAcception> AppointmentAcceptions { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
